# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

gcp_settings:
  # GCP project number.
  project_number: 'XXXXXXXXXX'

  # Google Cloud Storage bucket, example: 'exemplary_client_test_external'
  gcs_bucket: 'exemplary_client_test_external'

translation_config:
  # The translation type needs to be one of these: Translation_Teradata2BQ, Translation_Redshift2BQ,Translation_Bteq2BQ,
  # Translation_Oracle2BQ, Translation_HiveQL2BQ, Translation_SparkSQL2BQ, Translation_Snowflake2BQ,
  # Translation_Netezza2BQ, Translation_AzureSynapse2BQ, Translation_Vertica2BQ.
  translation_type: Translation_Teradata2BQ
  location: 'us'

  # [Optional field] The default database name to fully qualify SQL objects when their database name is missing.
  # default_database: __DEFAULT_DATABASE__

  # [Optional field] The schema search path. When SQL objects are missing schema name, translation engine will search through this list to find the value.
  # schema_search_path:
  #   - __DEFAULT_SCHEMA__

  # Set this to True (default) to clean up the temporary data in the '.tmp_processed' folder after job finishes.
  clean_up_tmp_files: False