# TO FORMAT: run ./gradlew versionCatalogFormat
# TO UPGRADE: run ./gradlew versionCatalogUpdate (accepts an --interactive flag)
[versions]
apache-avro = "1.11.4"
apache-commons-compress = "1.27.1"
apache-commons-csv = "1.13.0"
apache-commons-lang3 = "3.18.0"
ascii-table = "1.8.0"
auto-service = "1.1.1"
auto-value = "1.11.0"
aws-java-sdk = "1.12.791"
ben-manes-versions-plugin = "0.52.0"
cel = "0.8.0"
checkerframework = "3.51.0"
commons-io = "2.19.0"
datanucleus-api-jdo = "4.2.5"
datanucleus-core = "4.1.17"
datanucleus-javax-jdo = "3.2.1"
datanucleus-rdbms = "4.1.20"
google-cloud-bigquery = "2.55.2"
google-cloud-bigquerydatatransfer = "2.59.0"
google-cloud-kms = "2.78.0"
google-cloud-logging = "3.21.4"
google-cloud-nio = "0.127.30"
gradle-info-plugin = "11.4.1"
gradle-license-report = "2.8"
guava = "32.1.2-jre"
hadoop = "3.4.2"
hikaricp = "4.0.3"
hive = "3.1.3"
httpclient5 = "5.4.3"
jackson = "2.19.0"
javax-annotation-api = "1.3.2"
jcip = "1.0-1"
jcl-over-slf4j = "2.0.17"
jdiagnostics = "1.0.7"
joda-time = "2.14.0"
jopt-simple = "5.0.4"
jsr305 = "3.0.2"
junit = "4.13.2"
junit-jupiter = "5.12.0"
log4j-over-slf4j = "2.0.16"
logback = "1.3.16"
mockito = "4.11.0"
postgresql = "42.7.8"
protobuf = "3.25.6"
rate-limited-logger = "2.0.2"
re2j = "1.8"
redshift-jdbc = "2.1.0.32"
shadow-plugin = "8.1.1"
slf4j = "1.7.36"
snakeyaml = "2.5"
snowflake = "3.27.1"
spotless-plugin-gradle = "6.4.1"
spring = "5.3.39"
sqlite-jdbc = "3.50.3.0"
system-rules = "1.19.0"
tez = "0.10.0"
thrift = "0.20.0"
truth = "1.4.4"
version-catalog-update-plugin = "0.8.5"
wiremock = "2.27.2"
asm = "9.8"
avro = "1.11.4"
fastutil = "8.5.15"
h2 = "2.2.224"
parquet = "1.15.2"
spring-main = "6.1.10"
google = "2.50.0"
oozie-client = "5.2.1"
amazon = "2.31.16"
cloudrun = "0.60.0"
jna = "5.17.0"
jetty-server = "9.4.58.v20250814"
netty-handler = "4.1.127.Final"
dnsjava = "3.6.3"
nimbus-jose-jwt = "10.5"
io-grpc = "1.76.1"
xerces = "2.12.2"
zookeeper = "3.9.4"
common-configuration2 = "2.12.0"

[libraries]
async-profiler = {module = "tools.profiler:async-profiler", version="4.2"}
apache-avro = { module = "org.apache.avro:avro", version.ref = "apache-avro" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "apache-commons-compress" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "apache-commons-csv" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
ascii-table = { module = "com.github.freva:ascii-table", version.ref = "ascii-table"}
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
auto-value = { module = "com.google.auto.value:auto-value", version.ref = "auto-value" }
auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "auto-value" }
aws-java-sdk-cloudwatch = { module = "com.amazonaws:aws-java-sdk-cloudwatch", version.ref = "aws-java-sdk" }
aws-java-sdk-redshift = { module = "com.amazonaws:aws-java-sdk-redshift", version.ref = "aws-java-sdk" }
aws-java-sdk-redshiftserverless = { module = "com.amazonaws:aws-java-sdk-redshiftserverless", version.ref = "aws-java-sdk" }
cel = { module = "dev.cel:cel", version.ref = "cel" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
datanucleus-api-jdo = { module = "org.datanucleus:datanucleus-api-jdo", version.ref = "datanucleus-api-jdo" }
datanucleus-core = { module = "org.datanucleus:datanucleus-core", version.ref = "datanucleus-core" }
datanucleus-javax-jdo = { module = "org.datanucleus:javax.jdo", version.ref = "datanucleus-javax-jdo" }
datanucleus-rdbms = { module = "org.datanucleus:datanucleus-rdbms", version.ref = "datanucleus-rdbms" }
google-cloud-bigquery = { module = "com.google.cloud:google-cloud-bigquery", version.ref = "google-cloud-bigquery" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "io-grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "io-grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "io-grpc" }
grpc-auth = { module = "io.grpc:grpc-auth", version.ref = "io-grpc" }
grpc-opentelemetry = { module = "io.grpc:grpc-opentelemetry", version.ref = "io-grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "io-grpc" }
grpc-rls = { module = "io.grpc:grpc-rls", version.ref = "io-grpc" }
grpc-xds = { module = "io.grpc:grpc-xds", version.ref = "io-grpc" }
grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "io-grpc" }
google-cloud-bigquerydatatransfer = { module = "com.google.cloud:google-cloud-bigquerydatatransfer", version.ref = "google-cloud-bigquerydatatransfer" }
google-cloud-kms = { module = "com.google.cloud:google-cloud-kms", version.ref = "google-cloud-kms" }
google-cloud-logging = { module = "com.google.cloud:google-cloud-logging", version.ref = "google-cloud-logging"}
google-cloud-nio = { module = "com.google.cloud:google-cloud-nio", version.ref = "google-cloud-nio" }
google-cloud-storage-control = { module = "com.google.cloud:google-cloud-storage-control", version.ref = "google"}
gradle-info-plugin = { module = "com.netflix.nebula:gradle-info-plugin", version.ref = "gradle-info-plugin" }
gradle-license-report = { module = "com.github.jk1:gradle-license-report", version.ref = "gradle-license-report" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hadoop-auth = { module = "org.apache.hadoop:hadoop-auth", version.ref = "hadoop"}
hadoop-common = { module = "org.apache.hadoop:hadoop-common", version.ref = "hadoop" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version = "1.82" }
common-configuration2 = { module = "org.apache.commons:commons-configuration2", version.ref = "common-configuration2" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus-jose-jwt" }
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty-server" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty-handler" }
hadoop-hdfs-client = { module = "org.apache.hadoop:hadoop-hdfs-client", version.ref = "hadoop" }
harawata-appdirs = {module = "net.harawata:appdirs", version = "1.3.0"}
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
hive-common = { module = "org.apache.hive:hive-common", version.ref = "hive" }
hive-exec = { module = "org.apache.hive:hive-exec", version.ref = "hive" }
hive-jdbc = { module = "org.apache.hive:hive-jdbc", version.ref = "hive" }
hive-metastore = { module = "org.apache.hive:hive-metastore", version.ref = "hive" }
hive-service = { module = "org.apache.hive:hive-service", version.ref = "hive" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson"}
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-datatype-guava = { module = "com.fasterxml.jackson.datatype:jackson-datatype-guava", version.ref = "jackson" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
jcip-annotations = { module = "com.github.stephenc.jcip:jcip-annotations", version.ref = "jcip" }
jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "jcl-over-slf4j" }
jdiagnostics = { module = "org.anarres.jdiagnostics:jdiagnostics", version.ref = "jdiagnostics" }
joda-time = { module = "joda-time:joda-time", version.ref = "joda-time" }
jopt-simple = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt-simple" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
libthrift = { module = "org.apache.thrift:libthrift", version.ref = "thrift" }
log4j-over-slf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "log4j-over-slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf"}
rate-limited-logger = { module = "com.swrve:rate-limited-logger", version.ref = "rate-limited-logger" }
re2j = { module = "com.google.re2j:re2j", version.ref = "re2j" }
redshift-jdbc = { module = "com.amazon.redshift:redshift-jdbc42", version.ref = "redshift-jdbc" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
snowflake-jdbc = { module = "net.snowflake:snowflake-jdbc", version.ref = "snowflake" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless-plugin-gradle" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
system-rules = { module = "com.github.stefanbirkner:system-rules", version.ref = "system-rules" }
tez-common = { module = "org.apache.tez:tez-common", version.ref = "tez" }
tez-dag = { module = "org.apache.tez:tez-dag", version.ref = "tez" }
truth = { module = "com.google.truth:truth", version.ref = "truth"}
wiremock = { module = "com.github.tomakehurst:wiremock-standalone", version.ref = "wiremock" }
aws-s3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "amazon" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
avro = { group = "org.apache.avro", name = "avro", version.ref = "avro" }
commons-csv = { group = "org.apache.commons", name = "commons-csv", version = "1.11.0" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.18.0" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
google-cloud-storage = { group = "com.google.cloud", name = "google-cloud-storage", version.ref = "google" }
google-cloud-run = { group = "com.google.cloud", name = "google-cloud-run", version.ref = "cloudrun" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
parquet-generator = { group = "org.apache.parquet", name = "parquet-generator", version.ref = "parquet" }
parquet = { group = "org.apache.parquet", name = "parquet", version.ref = "parquet" }
oozie-client = { group = "org.apache.oozie", name = "oozie-client", version.ref = "oozie-client"}
xerces = { module = "xerces:xercesImpl", version.ref = "xerces"}
jna = { group = "net.java.dev.jna", "name" = "jna", version.ref = "jna"}
zookeeper = { module = "org.apache.zookeeper:zookeeper", version.ref = "zookeeper"}
hadoop-shaded-protobuf = { module = "org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_25", version = "1.5.0"}

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-plugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update-plugin" }
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
jmh-report = { id = "io.morethan.jmhreport", version = "0.9.6" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
test-logger = {id = "com.adarshr.test-logger", version="4.0.0"}